# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-12 21:37
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20170925_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=200)),
                ('start_text', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'db_table': 'mainpage',
            },
        ),
    ]
