# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-12 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20180512_2204'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mainpage',
            table='mainpage',
        ),
    ]
